apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: infrastructure
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Infrastructure components (cert-manager, ALB controller, monitoring, etc.)
  
  # Source repositories
  sourceRepos:
    - 'https://github.com/TomJennyDev/devops.git'
    - 'https://aws.github.io/eks-charts'
    - 'https://prometheus-community.github.io/helm-charts'
    - 'https://charts.jetstack.io'
  
  # Destination clusters and namespaces
  destinations:
    - namespace: 'argocd'
      server: 'https://kubernetes.default.svc'
    - namespace: 'kube-system'
      server: 'https://kubernetes.default.svc'
    - namespace: 'cert-manager'
      server: 'https://kubernetes.default.svc'
    - namespace: 'monitoring'
      server: 'https://kubernetes.default.svc'
    - namespace: 'ingress-nginx'
      server: 'https://kubernetes.default.svc'
  
  # Allowed cluster resources
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  
  # Namespace resource blacklist (prevent certain resources)
  namespaceResourceBlacklist:
    - group: ''
      kind: 'ResourceQuota'
    - group: ''
      kind: 'LimitRange'
  
  # Roles for RBAC
  roles:
    - name: infrastructure-admin
      description: Admin access to infrastructure project
      policies:
        - p, proj:infrastructure:infrastructure-admin, applications, *, infrastructure/*, allow
      groups:
        - infrastructure-team
    
    - name: infrastructure-readonly
      description: Read-only access to infrastructure project
      policies:
        - p, proj:infrastructure:infrastructure-readonly, applications, get, infrastructure/*, allow
      groups:
        - developers
