apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  
  source:
    repoURL: https://kubernetes-sigs.github.io/external-dns/
    chart: external-dns
    targetRevision: 1.14.5
    helm:
      releaseName: external-dns
      values: |
        provider: aws
        
        # IAM Role for Service Account (IRSA)
        serviceAccount:
          create: true
          annotations:
            eks.amazonaws.com/role-arn: arn:aws:iam::ACCOUNT_ID:role/CLUSTER_NAME-external-dns-xxxxx  # Get from: terraform output external_dns_role_arn
        
        # AWS Configuration
        domainFilters:
          - example.com  # Update with your domain
          - subdomain.example.com  # Add subdomains if needed
        
        policy: sync  # or upsert-only
        
        sources:
          - service
          - ingress
        
        txtOwnerId: my-eks-cluster  # Update with cluster name
        
        # Resources
        resources:
          limits:
            cpu: 100m
            memory: 300Mi
          requests:
            cpu: 50m
            memory: 150Mi
        
        # Logging
        logLevel: info
        logFormat: json
  
  destination:
    server: https://kubernetes.default.svc
    namespace: external-dns
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
