apiVersion: v1
kind: Service
metadata:
  name: flowise-server
  labels:
    app: flowise
    component: server
spec:
  type: ClusterIP
  ports:
  - port: 3000
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: flowise
    component: server
