apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: flowise-server
  labels:
    app: flowise
    component: server
    release: prometheus  # Match with Prometheus operator release name
spec:
  selector:
    matchLabels:
      app: flowise
      component: server
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s
    scheme: http
