apiVersion: v1
kind: Service
metadata:
  name: flowise-ui
  labels:
    app: flowise
    component: ui
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: flowise
    component: ui
