# ============================================
# APP OF APPS PATTERN - DEV ENVIRONMENT
# ============================================
# Pattern: App of Apps (ArgoCD best practice)
# Official Docs: https://argo-cd.readthedocs.io/en/stable/operator-manual/cluster-bootstrapping/
# Reference: https://github.com/argoproj/argocd-example-apps/tree/master/apps
#
# Specification:
#   API: argoproj.io/v1alpha1
#   Kind: Application (ArgoCD CRD)
#   Source: https://github.com/argoproj/argo-cd/blob/master/manifests/crds/application-crd.yaml
#
# This file deploys multiple applications using Kustomize overlays
# Based on: https://argo-cd.readthedocs.io/en/stable/user-guide/kustomize/
# ============================================

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: system-apps-dev-kustomize
  namespace: argocd
  labels:
    environment: dev
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  
  sources:
    # Prometheus + Grafana Stack
    - repoURL: https://github.com/TomJennyDev/devops.git
      targetRevision: main
      path: argocd/system-apps-kustomize/prometheus/overlays/dev
  
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
