# ==============================================================================
# External Secrets Operator - Lấy secrets từ AWS Secrets Manager
# ==============================================================================
#
# Cài đặt External Secrets Operator:
# helm repo add external-secrets https://charts.external-secrets.io
# helm install external-secrets external-secrets/external-secrets -n external-secrets-system --create-namespace
#
# ==============================================================================

---
# Step 1: Tạo SecretStore (kết nối đến AWS Secrets Manager)
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-secrets-manager
  namespace: kube-system
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-southeast-1
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets-sa  # Service account có IRSA

---
# Step 2: Tạo ExternalSecret (sync từ AWS Secrets Manager)
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: alb-controller-config
  namespace: kube-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  
  target:
    name: alb-controller-values  # Tên secret sẽ được tạo trong K8s
    creationPolicy: Owner
  
  data:
    - secretKey: clusterName
      remoteRef:
        key: eks/dev/alb-controller  # AWS Secrets Manager key
        property: clusterName
    
    - secretKey: vpcId
      remoteRef:
        key: eks/dev/alb-controller
        property: vpcId
    
    - secretKey: roleArn
      remoteRef:
        key: eks/dev/alb-controller
        property: roleArn

---
# Step 3: Tạo secrets trong AWS (chạy 1 lần)
# aws secretsmanager create-secret \
#   --name eks/dev/alb-controller \
#   --region ap-southeast-1 \
#   --secret-string '{
#     "clusterName": "my-eks-dev",
#     "vpcId": "vpc-0e6ca42c7851c46c4",
#     "roleArn": "arn:aws:iam::372836560690:role/my-eks-dev-aws-load-balancer-controller"
#   }'

---
# Step 4: ArgoCD Application không có values (lấy từ secret tự động)
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-load-balancer-controller
  namespace: argocd
spec:
  source:
    repoURL: https://aws.github.io/eks-charts
    chart: aws-load-balancer-controller
    targetRevision: 1.8.2
    helm:
      values: |
        clusterName: {{ .Values.clusterName }}
        vpcId: {{ .Values.vpcId }}
        serviceAccount:
          annotations:
            eks.amazonaws.com/role-arn: {{ .Values.roleArn }}
  
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
