# ==============================================================================
# Sealed Secrets Example - Mã hóa secrets trong Git
# ==============================================================================
# 
# Cài đặt Sealed Secrets Controller:
# kubectl apply -f https://github.com/bitnami-labs/sealed-secrets/releases/download/v0.24.0/controller.yaml
#
# Cài đặt kubeseal CLI:
# brew install kubeseal  # macOS
# choco install kubeseal # Windows
#
# ==============================================================================

---
# Step 1: Tạo secret thông thường (KHÔNG commit vào Git)
apiVersion: v1
kind: Secret
metadata:
  name: alb-controller-values
  namespace: kube-system
type: Opaque
stringData:
  values.yaml: |
    clusterName: my-eks-dev
    vpcId: vpc-0e6ca42c7851c46c4
    serviceAccount:
      annotations:
        eks.amazonaws.com/role-arn: arn:aws:iam::372836560690:role/my-eks-dev-aws-load-balancer-controller

---
# Step 2: Mã hóa secret thành SealedSecret (AN TOÀN để commit vào Git)
# Chạy lệnh:
# kubectl create secret generic alb-controller-values \
#   --from-file=values.yaml=./values.yaml \
#   --namespace=kube-system \
#   --dry-run=client -o yaml | \
#   kubeseal -o yaml > sealed-secret.yaml
#
# Kết quả SealedSecret (ví dụ):
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: alb-controller-values
  namespace: kube-system
spec:
  encryptedData:
    values.yaml: AgBhW8YN5... # Encrypted data - AN TOÀN để commit vào Git
  template:
    metadata:
      name: alb-controller-values
      namespace: kube-system
    type: Opaque

---
# Step 3: ArgoCD Application sử dụng secret
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-load-balancer-controller
  namespace: argocd
spec:
  source:
    repoURL: https://aws.github.io/eks-charts
    chart: aws-load-balancer-controller
    targetRevision: 1.8.2
    helm:
      # Không có values inline - lấy từ secret
      valueFiles:
        - secrets://kube-system/alb-controller-values/values.yaml
  
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
