#!/bin/bash
# ==================================================
# Update AWS Load Balancer Controller Config
# ==================================================
# This script updates ALB Controller values.yaml with
# actual values from Terraform outputs
# 
# Usage: ./update-alb-controller-config.sh [environment]
# Example: ./update-alb-controller-config.sh dev

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV="${1:-dev}"  # Default to dev if not specified
TERRAFORM_DIR="$SCRIPT_DIR/../terraform-eks/environments/$ENV"
VALUES_FILE="$SCRIPT_DIR/../argocd/system-apps-kustomize/aws-load-balancer-controller/overlays/$ENV/values.yaml"

# Colors
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

echo -e "${BLUE}========================================${NC}"
echo -e "${BLUE}Update ALB Controller Configuration${NC}"
echo -e "${BLUE}Environment: $ENV${NC}"
echo -e "${BLUE}========================================${NC}"
echo ""

# Check if environment exists
if [ ! -d "$TERRAFORM_DIR" ]; then
  echo -e "${RED}❌ Terraform directory not found: $TERRAFORM_DIR${NC}"
  echo -e "${YELLOW}Available environments: dev, staging, production${NC}"
  exit 1
fi

if [ ! -f "$VALUES_FILE" ]; then
  echo -e "${RED}❌ Values file not found: $VALUES_FILE${NC}"
  exit 1
fi

# ==================================================
# Get Terraform outputs
# ==================================================
echo -e "${YELLOW}📋 Reading Terraform outputs from $ENV...${NC}"

cd "$TERRAFORM_DIR"

CLUSTER_NAME=$(terraform output -raw cluster_id 2>/dev/null || echo "")
VPC_ID=$(terraform output -raw vpc_id 2>/dev/null || echo "")
ALB_ROLE_ARN=$(terraform output -raw aws_load_balancer_controller_role_arn 2>/dev/null || echo "")
AWS_REGION="ap-southeast-1"
ACCOUNT_ID=$(echo "$ALB_ROLE_ARN" | cut -d':' -f5)

if [ -z "$CLUSTER_NAME" ] || [ -z "$VPC_ID" ] || [ -z "$ALB_ROLE_ARN" ]; then
  echo -e "${RED}❌ Failed to get Terraform outputs${NC}"
  echo -e "${YELLOW}Make sure you run 'terraform apply' first${NC}"
  exit 1
fi

echo -e "${GREEN}✅ Cluster Name: $CLUSTER_NAME${NC}"
echo -e "${GREEN}✅ VPC ID: $VPC_ID${NC}"
echo -e "${GREEN}✅ Region: $AWS_REGION${NC}"
echo -e "${GREEN}✅ Account ID: $ACCOUNT_ID${NC}"
echo -e "${GREEN}✅ ALB Role ARN: $ALB_ROLE_ARN${NC}"
echo ""

# ==================================================
# Update values.yaml
# ==================================================
echo -e "${YELLOW}📝 Updating values.yaml...${NC}"

# Backup original
cp "$VALUES_FILE" "$VALUES_FILE.bak"

# Create temporary file with updated values
cat > "$VALUES_FILE" <<EOF
# ==================================================
# AWS Load Balancer Controller - ${ENV^} Environment Values
# ==================================================
# Auto-generated by update-alb-controller-config.sh
# Generated at: $(date)

# Cluster configuration
clusterName: $CLUSTER_NAME
region: $AWS_REGION
vpcId: $VPC_ID

# IAM Role for IRSA
iamRoleArn: $ALB_ROLE_ARN

# Controller settings
replicaCount: 2  # HA: 2 replicas

# Resource limits
resources:
  limits:
    cpu: 500m
    memory: 1Gi
  requests:
    cpu: 200m
    memory: 512Mi
EOF

echo -e "${GREEN}✅ Updated $VALUES_FILE${NC}"

# ==================================================
# Update deployment-patch.yaml args
# ==================================================
echo -e "${YELLOW}📝 Updating deployment-patch.yaml...${NC}"

DEPLOYMENT_PATCH="$SCRIPT_DIR/../argocd/system-apps-kustomize/aws-load-balancer-controller/overlays/$ENV/deployment-patch.yaml"

if [ -f "$DEPLOYMENT_PATCH" ]; then
  cp "$DEPLOYMENT_PATCH" "$DEPLOYMENT_PATCH.bak"
  
  sed -i "s|--cluster-name=.*|--cluster-name=$CLUSTER_NAME|g" "$DEPLOYMENT_PATCH"
  sed -i "s|--aws-region=.*|--aws-region=$AWS_REGION|g" "$DEPLOYMENT_PATCH"
  sed -i "s|--aws-vpc-id=.*|--aws-vpc-id=$VPC_ID|g" "$DEPLOYMENT_PATCH"
  
  echo -e "${GREEN}✅ Updated $DEPLOYMENT_PATCH${NC}"
fi

# ==================================================
# Update serviceaccount-patch.yaml
# ==================================================
echo -e "${YELLOW}📝 Updating serviceaccount-patch.yaml...${NC}"

SA_PATCH="$SCRIPT_DIR/../argocd/system-apps-kustomize/aws-load-balancer-controller/overlays/$ENV/serviceaccount-patch.yaml"

if [ -f "$SA_PATCH" ]; then
  cp "$SA_PATCH" "$SA_PATCH.bak"
  
  sed -i "s|eks.amazonaws.com/role-arn: arn:aws:iam::.*:role/.*|eks.amazonaws.com/role-arn: $ALB_ROLE_ARN|g" "$SA_PATCH"
  
  echo -e "${GREEN}✅ Updated $SA_PATCH${NC}"
fi

# ==================================================
# Summary
# ==================================================
echo ""
echo -e "${BLUE}========================================${NC}"
echo -e "${GREEN}✅ Configuration Updated Successfully!${NC}"
echo -e "${BLUE}========================================${NC}"
echo ""
echo -e "${YELLOW}📋 Updated files:${NC}"
echo "  1. $VALUES_FILE"
[ -f "$DEPLOYMENT_PATCH" ] && echo "  2. $DEPLOYMENT_PATCH"
[ -f "$SA_PATCH" ] && echo "  3. $SA_PATCH"
echo ""
echo -e "${YELLOW}📦 Backups created with .bak extension${NC}"
echo ""
echo -e "${YELLOW}🚀 Next steps:${NC}"
echo "  1. Review changes: git diff"
echo "  2. Commit changes: git add . && git commit -m 'Update ALB Controller config for $ENV from Terraform'"
echo "  3. Deploy ALB Controller: kubectl apply -k argocd/system-apps-kustomize/aws-load-balancer-controller/overlays/$ENV/"
echo ""
echo -e "${GREEN}✅ Done!${NC}"
